# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build verdacci offline-storage Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v2
        id: git_checkout
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        id: buildAndPushImage
        with:
          image: jayxuz/verdaccio-offline-storage
          tags: 5.3.1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
